<a href="https://colab.research.google.com/github/AshuPraja13/Data-Science/blob/main/Credit_Score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Predict the Credit Score of a customer using given customer information.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
df = pd.read_csv("credit_score.csv")

In [22]:
data=df.copy()

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10157 entries, 0 to 10156
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        10157 non-null  object
 1   Customer_ID               10157 non-null  object
 2   Month                     10157 non-null  object
 3   Name                      9149 non-null   object
 4   Age                       10157 non-null  object
 5   SSN                       10157 non-null  object
 6   Occupation                10157 non-null  object
 7   Annual_Income             10157 non-null  object
 8   Monthly_Inhand_Salary     8663 non-null   float64
 9   Num_Bank_Accounts         10157 non-null  int64
 10  Num_Credit_Card           10157 non-null  int64
 11  Interest_Rate             10157 non-null  int64
 12  Num_of_Loan               10157 non-null  object
 13  Type_of_Loan              8949 non-null   object
 14  Delay_from_due_date       10157 non-null  int64
 15  Num_of_Delayed_Payment    9441 non-null   object
 16  Changed_Credit_Limit      10157 non-null  object
 17  Num_Credit_Inquiries      9946 non-null   float64
 18  Credit_Mix                10157 non-null  object
 19  Outstanding_Debt          10157 non-null  object
 20  Credit_Utilization_Ratio  10157 non-null  float64
 21  Credit_History_Age        9211 non-null   object
 22  Payment_of_Min_Amount     10157 non-null  object
 23  Total_EMI_per_month       10157 non-null  float64
 24  Amount_invested_monthly   9718 non-null   object
 25  Payment_Behaviour         10157 non-null  object
 26  Monthly_Balance           10021 non-null  object
 27  Credit_Score              10156 non-null  object
dtypes: float64(4), int64(4), object(20)
memory usage: 2.2+ MB

In [24]:
df.isnull().sum()

ID                             0
Customer_ID                    0
Month                          0
Name                        1008
Age                            0
SSN                            0
Occupation                     0
Annual_Income                  0
Monthly_Inhand_Salary       1494
Num_Bank_Accounts              0
Num_Credit_Card                0
Interest_Rate                  0
Num_of_Loan                    0
Type_of_Loan                1208
Delay_from_due_date            0
Num_of_Delayed_Payment       716
Changed_Credit_Limit           0
Num_Credit_Inquiries         211
Credit_Mix                     0
Outstanding_Debt               0
Credit_Utilization_Ratio       0
Credit_History_Age           946
Payment_of_Min_Amount          0
Total_EMI_per_month            0
Amount_invested_monthly      439
Payment_Behaviour              0
Monthly_Balance              136
Credit_Score                   1
dtype: int64

In [25]:
df.head()

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [26]:
df.tail()

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
10152,0x517e,CUS_0x6f4d,January,NaN,51,433-42-8444,Lawyer,148841.56_,12696.463333,1,...,_,1095.81,32.880213,NaN,No,186.357774,100.10501917967369,High_spent_Large_value_payments,1223.18353981116,Poor
10153,0x517f,CUS_0x6f4d,February,NaN,3715,433-42-8444,Lawyer,148841.56,12696.463333,1,...,Good,1095.81,34.151482,16 Years and 4 Months,No,186.357774,547.3349923409365,!@9#%8,815.9535666498973,Standard
10154,0x5180,CUS_0x6f4d,March,Luke Bakerg,51,#F%$D@*&8,_______,148841.56,12696.463333,1,...,_,1095.81,29.341001,16 Years and 5 Months,No,186.357774,996.1505864442636,Low_spent_Large_value_payments,357.13797254657027,Poor
10155,0x5181,CUS_0x6f4d,April,Luke Bakerg,51,433-42-8444,Lawyer,148841.56,12696.463333,1,...,Good,1095.81,34.897891,16 Years and 6 Months,No,186.357774,NaN,High_spent_Medium_value_payments,1161.6384681398379,Poor
10156,0x5182,CUS_0x6f4d,May,Luke Bakerg,51,433-42-8444,Lawyer,148841.56,12696.463333,1,...,Good,1095.81,40.299671,16 Years and 7 Months,NM,186.357774,258.15366841753945,High_spent_Large_value_paymen,NaN,NaN

In [27]:
x = ['Age','Annual_Income','Num_of_Loan', 'Num_of_Delayed_Payment', 'Outstanding_Debt', 'Amount_invested_monthly', 'Monthly_Balance']
for i in x:
  df[f'{i}']=pd.to_numeric(df[f'{i}'],errors='coerce')

In [28]:
df.Credit_Mix = df.Credit_Mix.replace({"_":np.nan})

In [29]:
df = df.fillna(method='ffill')
df = df.fillna(method='bfill')

In [30]:
df.Month = df.Month.map({'January': 0, 'February': 1, 'March': 3, 'April': 4,'May':5,'June':6,'July': 7,'August':8})

In [31]:
df = df.iloc[:,4:]

In [32]:
for i in range(len(df.Credit_History_Age.values)):
  df.Credit_History_Age[i] = int(df.Credit_History_Age.values[i].split('Years and ')[0])*12+ int(df.Credit_History_Age.values[i].split('Years and ')[1].replace(' Months',''))

<ipython-input-32-46cef9eca1ea>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Credit_History_Age[i] = int(df.Credit_History_Age.values[i].split('Years and ')[0])*12+ int(df.Credit_History_Age.values[i].split('Years and ')[1].replace(' Months',''))

In [33]:
df['Credit_History_Age'] = pd.to_numeric(df['Credit_History_Age'])

In [34]:
df = df.drop(columns='SSN')

In [35]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [36]:
a=[]
for i in df.columns:
  if df[f'{i}'].dtype == 'object':
    a.append(i)

In [37]:
a

['Occupation',
 'Type_of_Loan',
 'Changed_Credit_Limit',
 'Credit_Mix',
 'Payment_of_Min_Amount',
 'Payment_Behaviour',
 'Credit_Score']

In [38]:
df['Occupation']= le.fit_transform(df['Occupation'])
df["Changed_Credit_Limit"] = le.fit_transform(df['Changed_Credit_Limit'])
df['Credit_Mix'] = le.fit_transform(df['Credit_Mix'])
df['Payment_of_Min_Amount'] = le.fit_transform(df['Payment_of_Min_Amount'])
df['Type_of_Loan'] = le.fit_transform(df['Type_of_Loan'])
df['Payment_Behaviour'] = le.fit_transform(df['Payment_Behaviour'])
df['Credit_Score'] = le.fit_transform(df['Credit_Score'])

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10157 entries, 0 to 10156
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       10157 non-null  float64
 1   Occupation                10157 non-null  int64
 2   Annual_Income             10157 non-null  float64
 3   Monthly_Inhand_Salary     10157 non-null  float64
 4   Num_Bank_Accounts         10157 non-null  int64
 5   Num_Credit_Card           10157 non-null  int64
 6   Interest_Rate             10157 non-null  int64
 7   Num_of_Loan               10157 non-null  float64
 8   Type_of_Loan              10157 non-null  int64
 9   Delay_from_due_date       10157 non-null  int64
 10  Num_of_Delayed_Payment    10157 non-null  float64
 11  Changed_Credit_Limit      10157 non-null  int64
 12  Num_Credit_Inquiries      10157 non-null  float64
 13  Credit_Mix                10157 non-null  int64
 14  Outstanding_Debt          10157 non-null  float64
 15  Credit_Utilization_Ratio  10157 non-null  float64
 16  Credit_History_Age        10157 non-null  int64
 17  Payment_of_Min_Amount     10157 non-null  int64
 18  Total_EMI_per_month       10157 non-null  float64
 19  Amount_invested_monthly   10157 non-null  float64
 20  Payment_Behaviour         10157 non-null  int64
 21  Monthly_Balance           10157 non-null  float64
 22  Credit_Score              10157 non-null  int64
dtypes: float64(11), int64(12)
memory usage: 1.8 MB

In [40]:
df

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,23.0,12,19114.12,1824.843333,3,4,3,4.0,23,3,...,1,809.98,26.822620,265,1,49.574949,80.415295,4,312.494089,0
1,23.0,12,19114.12,1824.843333,3,4,3,4.0,23,-1,...,1,809.98,31.944960,265,1,49.574949,118.280222,5,284.629162,0
2,-500.0,12,19114.12,1824.843333,3,4,3,4.0,23,3,...,1,809.98,28.609352,267,1,49.574949,81.699521,6,331.209863,0
3,23.0,12,19114.12,1824.843333,3,4,3,4.0,23,5,...,1,809.98,31.377862,268,1,49.574949,199.458074,7,223.451310,0
4,23.0,12,19114.12,1824.843333,3,4,3,4.0,23,6,...,1,809.98,24.797347,269,1,49.574949,41.420153,3,341.489231,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10152,51.0,7,20051.92,12696.463333,1,6,7,3.0,264,10,...,1,1095.81,32.880213,305,1,186.357774,100.105019,2,1223.183540,1
10153,3715.0,7,148841.56,12696.463333,1,6,7,3.0,264,10,...,1,1095.81,34.151482,196,1,186.357774,547.334992,0,815.953567,2
10154,51.0,15,148841.56,12696.463333,1,6,7,3.0,264,14,...,1,1095.81,29.341001,197,1,186.357774,996.150586,5,357.137973,1
10155,51.0,7,148841.56,12696.463333,1,6,7,3.0,264,10,...,1,1095.81,34.897891,198,1,186.357774,996.150586,3,1161.638468,1
10156,51.0,7,148841.56,12696.463333,1,6,7,3.0,264,13,...,1,1095.81,40.299671,199,0,186.357774,258.153668,1,1161.638468,1

In [41]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [42]:
# vif = pd.DataFrame()
# vif['features'] = df.iloc[:,:-1].columns
# for i in range(len(df.iloc[:,:-1].columns)):
#   vif['vif factor'] = (variance_inflation_factor(df.iloc[:,:-1].values,i))

In [43]:
# vif

In [44]:
X = df.iloc[:,:-1]
vif = pd.DataFrame()
vif['features'] = X.columns
vif['vif'] = [variance_inflation_factor(X.values,i) for i in range(len(X.columns))]
vif

                    features        vif
0                        Age   1.029510
1                 Occupation   3.715796
2              Annual_Income   1.019022
3      Monthly_Inhand_Salary  15.932854
4          Num_Bank_Accounts   1.024731
5            Num_Credit_Card   1.034315
6              Interest_Rate   1.026582
7                Num_of_Loan   1.005549
8               Type_of_Loan   4.016391
9        Delay_from_due_date   4.831552
10    Num_of_Delayed_Payment   1.022077
11      Changed_Credit_Limit   4.483588
12      Num_Credit_Inquiries   1.022422
13                Credit_Mix   4.972407
14          Outstanding_Debt   5.312911
15  Credit_Utilization_Ratio  26.254326
16        Credit_History_Age   9.567013
17     Payment_of_Min_Amount   6.139785
18       Total_EMI_per_month   1.029683
19   Amount_invested_monthly   6.372644
20         Payment_Behaviour   6.131686
21           Monthly_Balance  16.763067

In [45]:
df=df.drop(columns='Credit_Utilization_Ratio')
X = df.iloc[:,:-1]
vif = pd.DataFrame()
vif['features'] = X.columns
vif['vif'] = [variance_inflation_factor(X.values,i) for i in range(len(X.columns))]

In [46]:
df=df.drop(columns='Monthly_Inhand_Salary')
X = df.iloc[:,:-1]
vif = pd.DataFrame()
vif['features'] = X.columns
vif['vif'] = [variance_inflation_factor(X.values,i) for i in range(len(X.columns))]

In [47]:
df=df.drop(columns='Credit_History_Age')
X = df.iloc[:,:-1]
vif = pd.DataFrame()
vif['features'] = X.columns
vif['vif'] = [variance_inflation_factor(X.values,i) for i in range(len(X.columns))]

In [48]:
df=df.drop(columns='Payment_of_Min_Amount')
X = df.iloc[:,:-1]
vif = pd.DataFrame()
vif['features'] = X.columns
vif['vif'] = [variance_inflation_factor(X.values,i) for i in range(len(X.columns))]

In [49]:
df

,Age,Occupation,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,23.0,12,19114.12,3,4,3,4.0,23,3,7.0,414,4.0,1,809.98,49.574949,80.415295,4,312.494089,0
1,23.0,12,19114.12,3,4,3,4.0,23,-1,7.0,414,4.0,1,809.98,49.574949,118.280222,5,284.629162,0
2,-500.0,12,19114.12,3,4,3,4.0,23,3,7.0,1951,4.0,1,809.98,49.574949,81.699521,6,331.209863,0
3,23.0,12,19114.12,3,4,3,4.0,23,5,4.0,1614,4.0,1,809.98,49.574949,199.458074,7,223.451310,0
4,23.0,12,19114.12,3,4,3,4.0,23,6,4.0,414,4.0,1,809.98,49.574949,41.420153,3,341.489231,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10152,51.0,7,20051.92,1,6,7,3.0,264,10,6.0,347,3.0,1,1095.81,186.357774,100.105019,2,1223.183540,1
10153,3715.0,7,148841.56,1,6,7,3.0,264,10,7.0,1905,7.0,1,1095.81,186.357774,547.334992,0,815.953567,2
10154,51.0,15,148841.56,1,6,7,3.0,264,14,8.0,1951,7.0,1,1095.81,186.357774,996.150586,5,357.137973,1
10155,51.0,7,148841.56,1,6,7,3.0,264,10,6.0,347,7.0,1,1095.81,186.357774,996.150586,3,1161.638468,1
10156,51.0,7,148841.56,1,6,7,3.0,264,13,6.0,347,7.0,1,1095.81,186.357774,258.153668,1,1161.638468,1

In [50]:
y = pd.get_dummies(df.iloc[:,-1])

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,:-1],df.iloc[:,-1],train_size=0.7,random_state=10)

In [53]:
from sklearn.ensemble import RandomForestClassifier
rfc= RandomForestClassifier(n_estimators=100)

In [54]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [55]:
y_pred_rfc = rfc.predict(X_test)

In [56]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [57]:
accuracy_score(y_test,y_pred_rfc)

0.7949475065616798

In [58]:
print(confusion_matrix(y_test,y_pred_rfc))

[[ 414    2  129]
 [   2  757  142]
 [ 123  227 1252]]

In [59]:
df.iloc[:,-1].value_counts()

2    5280
1    3002
0    1875
Name: Credit_Score, dtype: int64

In [60]:
data.iloc[:,-1].value_counts()

Standard    5280
Poor        3001
Good        1875
Name: Credit_Score, dtype: int64

In [61]:
para = {'criterion':['gini', 'entropy'],
'max_depth':[5,None],
'max_features':['sqrt','log2']}
para

{'criterion': ['gini', 'entropy'],
 'max_depth': [5, None],
 'max_features': ['sqrt', 'log2']}

**Hyperparameter tuning**

In [62]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV

In [63]:
gs = GridSearchCV(rfc,param_grid=para,cv=10)

In [64]:
gs.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [5, None],
                         'max_features': ['sqrt', 'log2']})

In [65]:
pd.DataFrame(gs.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_max_features,params,split0_test_score,split1_test_score,...,split3_test_score,split4_test_score,split5_test_score,split6_test_score,split7_test_score,split8_test_score,split9_test_score,mean_test_score,std_test_score,rank_test_score
0,0.737624,0.012027,0.013107,0.000536,gini,5,sqrt,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.666667,0.691983,...,0.700422,0.676512,0.658228,0.673699,0.680731,0.701828,0.653521,0.676604,0.016233,6
1,0.854363,0.161395,0.015793,0.004433,gini,5,log2,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.675105,0.699015,...,0.694796,0.670886,0.670886,0.682138,0.686357,0.699015,0.645070,0.678290,0.016682,5
2,2.216437,0.623916,0.033218,0.012671,gini,None,sqrt,"{'criterion': 'gini', 'max_depth': None, 'max_...",0.805907,0.774965,...,0.815752,0.752461,0.789030,0.797468,0.798875,0.791842,0.795775,0.790689,0.016571,3
3,2.454062,0.515657,0.034964,0.006740,gini,None,log2,"{'criterion': 'gini', 'max_depth': None, 'max_...",0.805907,0.763713,...,0.790436,0.765120,0.807314,0.794655,0.790436,0.786217,0.794366,0.788719,0.013794,4
4,1.072548,0.200661,0.019538,0.009869,entropy,5,sqrt,"{'criterion': 'entropy', 'max_depth': 5, 'max_...",0.663854,0.690577,...,0.682138,0.651195,0.656821,0.662447,0.663854,0.696203,0.645070,0.665351,0.017729,8
5,0.870302,0.010194,0.013419,0.001247,entropy,5,log2,"{'criterion': 'entropy', 'max_depth': 5, 'max_...",0.665260,0.687764,...,0.690577,0.656821,0.661041,0.658228,0.670886,0.696203,0.652113,0.667321,0.018338,7
6,2.452197,0.615912,0.030995,0.009543,entropy,None,sqrt,"{'criterion': 'entropy', 'max_depth': None, 'm...",0.810127,0.763713,...,0.808720,0.746835,0.801688,0.783404,0.808720,0.784810,0.798592,0.790689,0.020105,2
7,2.130615,0.292919,0.027421,0.005309,entropy,None,log2,"{'criterion': 'entropy', 'max_depth': None, 'm...",0.805907,0.772152,...,0.805907,0.756681,0.796062,0.796062,0.804501,0.790436,0.790141,0.791391,0.014954,1

In [66]:
gs.best_params_

{'criterion': 'entropy', 'max_depth': None, 'max_features': 'log2'}

In [67]:
gs.score(X_test,y_test)

0.7982283464566929

In [68]:
from scipy.stats import randint as sp_randint

In [69]:
param_dist = {"max_depth": [3, None],
              "max_features": sp_randint(1, 11),
              "min_samples_split": sp_randint(2, 11),
              "min_samples_leaf": sp_randint(1, 11),
              "bootstrap": [True, False],
              "criterion": ["gini", "entropy"]}

In [70]:
rs= RandomizedSearchCV(rfc,param_distributions=param_dist,n_iter=8,cv=10)

In [71]:
rs.fit(X_train,y_train)

RandomizedSearchCV(cv=10, estimator=RandomForestClassifier(), n_iter=8,
                   param_distributions={'bootstrap': [True, False],
                                        'criterion': ['gini', 'entropy'],
                                        'max_depth': [3, None],
                                        'max_features': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x797ae8548790>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x797ae8548c70>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x797ae85493c0>})

In [72]:
rs.best_params_

{'bootstrap': True,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': 9,
 'min_samples_leaf': 3,
 'min_samples_split': 10}

In [73]:
pd.DataFrame(rs.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_bootstrap,param_criterion,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,...,split3_test_score,split4_test_score,split5_test_score,split6_test_score,split7_test_score,split8_test_score,split9_test_score,mean_test_score,std_test_score,rank_test_score
0,0.883125,0.161560,0.023472,0.004028,False,entropy,None,1,8,8,...,0.766526,0.729958,0.744023,0.752461,0.756681,0.744023,0.752113,0.751723,0.010490,6
1,2.861214,0.416584,0.019947,0.002049,True,entropy,None,8,9,5,...,0.791842,0.756681,0.772152,0.772152,0.777778,0.769339,0.797183,0.779437,0.011888,5
2,0.907004,0.129049,0.013226,0.002559,False,gini,3,6,1,4,...,0.644163,0.632911,0.635724,0.639944,0.654008,0.679325,0.618310,0.644391,0.016315,7
3,0.529556,0.040045,0.013050,0.002356,True,entropy,3,3,2,10,...,0.638537,0.611814,0.597750,0.630098,0.634318,0.644163,0.615493,0.627372,0.015052,8
4,3.573695,0.324298,0.023560,0.003569,True,entropy,None,9,3,10,...,0.797468,0.762307,0.787623,0.784810,0.794655,0.789030,0.804225,0.791815,0.012693,1
5,2.407493,0.212013,0.020746,0.002417,True,gini,None,8,8,10,...,0.789030,0.749648,0.779184,0.780591,0.779184,0.776371,0.807042,0.781548,0.013571,4
6,3.060320,0.307242,0.020849,0.002131,True,gini,None,10,7,10,...,0.783404,0.760900,0.776371,0.786217,0.784810,0.777778,0.797183,0.783234,0.009651,3
7,4.101890,0.383969,0.021539,0.000613,True,entropy,None,10,1,10,...,0.798875,0.759494,0.796062,0.797468,0.793249,0.791842,0.802817,0.790549,0.014131,2

In [74]:
rs.score(X_test,y_test)

0.7880577427821522